package com.example.apptracker.ui.theme.yinyang

import androidx.compose.ui.graphics.Color

val primary = Color(0xFF000000)
val onPrimary = Color(0xFFFFFFFF)
val primaryContainer = Color(0xFF000000)
val onPrimaryContainer = Color(0xFFFFFFFF)
val secondary = Color(0xFF000000)
val onSecondary = Color(0xFFFFFFFF)
val secondaryContainer = Color(0xFFDDDDDD)
val onSecondaryContainer = Color(0xFF0C0C0C)
val tertiary = Color(0xFFFFFFFF)
val onTertiary = Color(0xFF000000)
val tertiaryContainer = Color(0xFFD8E2FF)
val onTertiaryContainer = Color(0xFF001947)
val background = Color(0xFFFDFDFD)
val onBackground = Color(0xFF222222)
val surface = Color(0xFFFDFDFD)
val onSurface = Color(0xFF222222)
val surfaceVariant = Color(0xFFEDEDED)
val onSurfaceVariant = Color(0xFF515151)
val outline = Color(0xFF838383)
val inverseOnSurface = Color(0xFFF4F4F4)
val inverseSurface = Color(0xFF333333)
val primaryInverse = Color(0xFFA6A6A6)

val darkPrimary = Color(0xFFFFFFFF)
val darkOnPrimary = Color(0xFF5A5A5A)
val darkPrimaryContainer = Color(0xFFFFFFFF)
val darkOnPrimaryContainer = Color(0xFF000000)
val darkSecondary = Color(0xFFFFFFFF)
val darkOnSecondary = Color(0xFF5A5A5A)
val darkSecondaryContainer = Color(0xFF717171)
val darkOnSecondaryContainer = Color(0xFFE4E4E4)
val darkTertiary = Color(0xFF000000)
val darkOnTertiary = Color(0xFFFFFFFF)
val darkTertiaryContainer = Color(0xFF00419E)
val darkOnTertiaryContainer = Color(0xFFD8E2FF)
val darkBackground = Color(0xFF1E1E1E)
val darkOnBackground = Color(0xFFE6E6E6)
val darkSurface = Color(0xFF1E1E1E)
val darkOnSurface = Color(0xFFE6E6E6)
val darkSurfaceVariant = Color(0xFF4E4E4E)
val darkOnSurfaceVariant = Color(0xFFD1D1D1)
val darkOutline = Color(0xFF999999)
val darkInverseOnSurface = Color(0xFF1E1E1E)
val darkInverseSurface = Color(0xFFE6E6E6)
val darkPrimaryInverse = Color(0xFFCECECE)