package com.example.apptracker.ui.theme.midnightdusk

import androidx.compose.ui.graphics.Color

val primary = Color(0xFFBB0054)
val onPrimary = Color(0xFFFFFFFF)
val primaryContainer = Color(0xFFFFD9E1)
val onPrimaryContainer = Color(0xFF3F0017)
val secondary = Color(0xFFBB0054)
val onSecondary = Color(0xFFFFFFFF)
val secondaryContainer = Color(0xFFFFD9E1)
val onSecondaryContainer = Color(0xFF3F0017)
val tertiary = Color(0xFF006638)
val onTertiary = Color(0xFFFFFFFF)
val tertiaryContainer = Color(0xFF00894b)
val onTertiaryContainer = Color(0xFF2D1600)
val background = Color(0xFFFFFBFF)
val onBackground = Color(0xFF1C1B1F)
val surface = Color(0xFFFFFBFF)
val onSurface = Color(0xFF1C1B1F)
val surfaceVariant = Color(0xFFF3DDE0)
val onSurfaceVariant = Color(0xFF524346)
val outline = Color(0xFF847376)
val inverseOnSurface = Color(0xFFF4F0F4)
val inverseSurface = Color(0xFF313033)
val primaryInverse = Color(0xFFFFB1C4)

val darkPrimary = Color(0xFFF02475)
val darkOnPrimary = Color(0xFFFFFFFF)
val darkPrimaryContainer = Color(0xFFBD1C5C)
val darkOnPrimaryContainer = Color(0xFFFFFFFF)
val darkSecondary = Color(0xFFF02475)
val darkOnSecondary = Color(0xFFFFFFFF)
val darkSecondaryContainer = Color(0xFFF02475)
val darkOnSecondaryContainer = Color(0xFFFFFFFF)
val darkTertiary = Color(0xFF55971C)
val darkOnTertiary = Color(0xFFFFFFFF)
val darkTertiaryContainer = Color(0xFF386412)
val darkOnTertiaryContainer = Color(0xFFE5E1E5)
val darkBackground = Color(0xFF16151D)
val darkOnBackground = Color(0xFFE5E1E5)
val darkSurface = Color(0xFF16151D)
val darkOnSurface = Color(0xFFE5E1E5)
val darkSurfaceVariant = Color(0xFF524346)
val darkOnSurfaceVariant = Color(0xFFD6C1C4)
val darkOutline = Color(0xFF9F8C8F)
val darkInverseSurface = Color(0xFF333043)
val darkInverseOnSurface = Color(0xFFFFFFFF)
val darkPrimaryInverse = Color(0xFFF02475)
val darkElevationOverlay = Color(0xFF2C0013)