package com.example.apptracker.ui.theme.strawberry

import androidx.compose.ui.graphics.Color

val primary = Color(0xFFB61E40)
val onPrimary = Color(0xFFFFFFFF)
val primaryContainer = Color(0xFFFFDADD)
val onPrimaryContainer = Color(0xFF40000D)
val secondary = Color(0xFFB61E40)
val onSecondary = Color(0xFFFFFFFF)
val secondaryContainer = Color(0xFFFFDADD)
val onSecondaryContainer = Color(0xFF40000D)
val tertiary = Color(0xFF775930)
val onTertiary = Color(0xFFFFFFFF)
val tertiaryContainer = Color(0xFFFFDDB1)
val onTertiaryContainer = Color(0xFF2A1800)
val background = Color(0xFFFCFCFC)
val onBackground = Color(0xFF201A1A)
val surface = Color(0xFFFCFCFC)
val onSurface = Color(0xFF201A1A)
val surfaceVariant = Color(0xFFF4DDDD)
val onSurfaceVariant = Color(0xFF534344)
val outline = Color(0xFF857374)
val inverseOnSurface = Color(0xFFFBEDED)
val inverseSurface = Color(0xFF362F2F)
val primaryInverse = Color(0xFFFFB2B9)

val darkPrimary = Color(0xFFFFB2B9)
val darkOnPrimary = Color(0xFF67001B)
val darkPrimaryContainer = Color(0xFF91002A)
val darkOnPrimaryContainer = Color(0xFFFFDADD)
val darkSecondary = Color(0xFFFFB2B9)
val darkOnSecondary = Color(0xFF67001B)
val darkSecondaryContainer = Color(0xFF91002A)
val darkOnSecondaryContainer = Color(0xFFFFDADD)
val darkTertiary = Color(0xFFE8C08E)
val darkOnTertiary = Color(0xFF432C06)
val darkTertiaryContainer = Color(0xFF5D421B)
val darkOnTertiaryContainer = Color(0xFFFFDDB1)
val darkBackground = Color(0xFF201A1A)
val darkOnBackground = Color(0xFFECDFDF)
val darkSurface = Color(0xFF201A1A)
val darkOnSurface = Color(0xFFECDFDF)
val darkSurfaceVariant = Color(0xFF534344)
val darkOnSurfaceVariant = Color(0xFFD7C1C2)
val darkOutline = Color(0xFFA08C8D)
val darkInverseOnSurface = Color(0xFF201A1A)
val darkInverseSurface = Color(0xFFECDFDF)
val darkPrimaryInverse = Color(0xFFB61E40)