package com.example.apptracker.ui.theme.yotsuba

import androidx.compose.ui.graphics.Color

val primary = Color(0xFFAE3200)
val onPrimary = Color(0xFFFFFFFF)
val primaryContainer = Color(0xFFFFDBCF)
val onPrimaryContainer = Color(0xFF3B0A00)
val secondary = Color(0xFFAE3200)
val onSecondary = Color(0xFFFFFFFF)
val secondaryContainer = Color(0xFFFFDBCF)
val onSecondaryContainer = Color(0xFF3B0A00)
val tertiary = Color(0xFF6B5E2F)
val onTertiary = Color(0xFFFFFFFF)
val tertiaryContainer = Color(0xFFF5E2A7)
val onTertiaryContainer = Color(0xFF231B00)
val background = Color(0xFFFCFCFC)
val onBackground = Color(0xFF211A18)
val surface = Color(0xFFFCFCFC)
val onSurface = Color(0xFF211A18)
val surfaceVariant = Color(0xFFF5DED8)
val onSurfaceVariant = Color(0xFF53433F)
val outline = Color(0xFF85736E)
val inverseOnSurface = Color(0xFFFBEEEB)
val inverseSurface = Color(0xFF362F2D)
val primaryInverse = Color(0xFFFFB59D)

val darkPrimary = Color(0xFFFFB59D)
val darkOnPrimary = Color(0xFF5F1600)
val darkPrimaryContainer = Color(0xFF862200)
val darkOnPrimaryContainer = Color(0xFFFFDBCF)
val darkSecondary = Color(0xFFFFB59D)
val darkOnSecondary = Color(0xFF5F1600)
val darkSecondaryContainer = Color(0xFF862200)
val darkOnSecondaryContainer = Color(0xFFFFDBCF)
val darkTertiary = Color(0xFFD7C68D)
val darkOnTertiary = Color(0xFF3A2F05)
val darkTertiaryContainer = Color(0xFF524619)
val darkOnTertiaryContainer = Color(0xFFF5E2A7)
val darkBackground = Color(0xFF211A18)
val darkOnBackground = Color(0xFFEDE0DD)
val darkSurface = Color(0xFF211A18)
val darkOnSurface = Color(0xFFEDE0DD)
val darkSurfaceVariant = Color(0xFF53433F)
val darkOnSurfaceVariant = Color(0xFFD8C2BC)
val darkOutline = Color(0xFFA08C87)
val darkInverseOnSurface = Color(0xFF211A18)
val darkInverseSurface = Color(0xFFEDE0DD)
val darkPrimaryInverse = Color(0xFFAE3200)