package com.example.apptracker.ui.theme.tidalwave

import androidx.compose.ui.graphics.Color

val primary = Color(0xFF006780)
val onPrimary = Color(0xFFffffff)
val primaryContainer = Color(0xFFB4D4DF)
val onPrimaryContainer = Color(0xFF001f28)
val secondary = Color(0xFF006780)
val onSecondary = Color(0xFFffffff)
val secondaryContainer = Color(0xFFb8eaff)
val onSecondaryContainer = Color(0xFF001f28)
val tertiary = Color(0xFF92f7bc)
val onTertiary = Color(0xFF001c3b)
val tertiaryContainer = Color(0xFFc3fada)
val onTertiaryContainer = Color(0xFF78ffd6)
val background = Color(0xFFfdfbff)
val onBackground = Color(0xFF001c3b)
val surface = Color(0xFFfdfbff)
val onSurface = Color(0xFF001c3b)
val surfaceVariant = Color(0xFFdce4e8)
val onSurfaceVariant = Color(0xFF40484c)
val outline = Color(0xFF70787c)
val inverseOnSurface = Color(0xFFffe3c4)
val inverseSurface = Color(0xFF020400)
val primaryInverse = Color(0xFFff987f)

val darkPrimary = Color(0xFF5ed4fc)
val darkOnPrimary = Color(0xFF003544)
val darkPrimaryContainer = Color(0xFF004d61)
val darkOnPrimaryContainer = Color(0xFFb8eaff)
val darkSecondary = Color(0xFF5ed4fc)
val darkOnSecondary = Color(0xFF003544)
val darkSecondaryContainer = Color(0xFF004d61)
val darkOnSecondaryContainer = Color(0xFFb8eaff)
val darkTertiary = Color(0xFF92f7bc)
val darkOnTertiary = Color(0xFF001c3b)
val darkTertiaryContainer = Color(0xFFc3fada)
val darkOnTertiaryContainer = Color(0xFF78ffd6)
val darkBackground = Color(0xFF001c3b)
val darkOnBackground = Color(0xFFd5e3ff)
val darkSurface = Color(0xFF001c3b)
val darkOnSurface = Color(0xFFd5e3ff)
val darkSurfaceVariant = Color(0xFF40484c)
val darkOnSurfaceVariant = Color(0xFFbfc8cc)
val darkOutline = Color(0xFF8a9296)
val darkInverseOnSurface = Color(0xFF001c3b)
val darkInverseSurface = Color(0xFFffe3c4)
val darkPrimaryInverse = Color(0xFFa12b03)