package com.example.apptracker.ui.theme.lavender

import androidx.compose.ui.graphics.Color

val primary = Color(0xFF7B46AF)
val onPrimary = Color(0xFFEDE2FF)
val primaryContainer = Color(0xFF7B46AF)
val onPrimaryContainer = Color(0xFFEDE2FF)
val secondary = Color(0xFF7B46AF)
val onSecondary = Color(0xFFEDE2FF)
val secondaryContainer = Color(0xFF7B46AF)
val onSecondaryContainer = Color(0xFFEDE2FF)
val tertiary = Color(0xFFEDE2FF)
val onTertiary = Color(0xFF7B46AF)
val tertiaryContainer = Color(0xFFEDE2FF)
val onTertiaryContainer = Color(0xFF7B46AF)
val background = Color(0xFFEDE2FF)
val onBackground = Color(0xFF1B1B22)
val surface = Color(0xFFEDE2FF)
val onSurface = Color(0xFF1B1B22)
val surfaceVariant = Color(0xFFB9B0CC)
val onSurfaceVariant = Color(0xFFD849454E)
val outline = Color(0xFF7B46AF)
val inverseOnSurface = Color(0xFFF3EFF4)
val inverseSurface = Color(0xFF313033)
val primaryInverse = Color(0xFFD6BAFF)

val darkPrimary = Color(0xFFA177FF)
val darkOnPrimary = Color(0xFF111129)
val darkPrimaryContainer = Color(0xFFA177FF)
val darkOnPrimaryContainer = Color(0xFF111129)
val darkSecondary = Color(0xFFA177FF)
val darkOnSecondary = Color(0xFF111129)
val darkSecondaryContainer = Color(0xFFA177FF)
val darkOnSecondaryContainer = Color(0xFF111129)
val darkTertiary = Color(0xFF5E25E1)
val darkOnTertiary = Color(0xFFE8E8E8)
val darkTertiaryContainer = Color(0xFF111129)
val darkOnTertiaryContainer = Color(0xFFDEE8FF)
val darkBackground = Color(0xFF111129)
val darkOnBackground = Color(0xFFDEE8FF)
val darkSurface = Color(0xFF111129)
val darkOnSurface = Color(0xFFDEE8FF)
val darkSurfaceVariant = Color(0xFF2CB6B6B6)
val darkOnSurfaceVariant = Color(0xFFE8E8E8)
val darkOutline = Color(0xFFA8905FFF)
val darkInverseOnSurface = Color(0xFFDEE8FF)
val darkInverseSurface = Color(0xFF221247)
val darkPrimaryInverse = Color(0xFFA177FF)